export const COLORS = {
  header: 'cyan',
  headerBg: 'black',
  tabActive: 'cyan',
  tabActiveBg: 'black',
  tabInactive: 'gray',
  tabInactiveBg: 'black',
  summaryLabel: 'gray',
  summaryValue: 'white',
  summaryCost: 'green',
  panelTitle: 'cyan',
  panelBorder: 'blue',
  progressBarFill: 'cyan',
  progressBarEmpty: 'gray',
  providerSession: 'yellow',
  providerWeekly: 'green',
  emptyState: 'gray',
  error: 'red',
  watchOn: 'green',
  watchOff: 'gray',
  cost: 'green',
  tokens: 'yellow',
  calls: 'white',
  agentActive: 'cyan',
  agentInactive: 'gray',
};
